### ISSUE TITLE
Récupérer le nombre de MP sur un seul onglet seulement

### ISSUE THREAD

**Issue by dorian-marchal** [CrazyJeux/NiceMPNotifs#4]
Pour éviter de faire _x_ requêtes toutes les 3 secondes (ce qui tue les perfs).

**Comment by CrazyJeux** [comment]
Cela sera corrigé avec la version contenant les notifs.

(As-tu lu ma réponse à ton PR 3 ?)

**Comment by dorian-marchal** [comment]
Yep, je le corrigerai sans doute dans une future màj.
Tu bosses sur le script en ce moment ?

J'allais faire une PR à l'instant :stuck_out_tongue:

**Comment by CrazyJeux** [comment]
Non, je ne bosse pas sur le script pour le moment. Tu n'auras pas à te soucier de conflits avant un petit moment car je suis visiblement encore plus occupé que toi. ^^
